# Generated by Django 5.1.6 on 2026-01-07 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0002_alter_patient_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("outpatient", "외래"),
                            ("inpatient", "입원"),
                            ("emergency", "응급"),
                        ],
                        max_length=20,
                        verbose_name="진료 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "예정"),
                            ("in-progress", "진행중"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[("neurology", "신경과"), ("neurosurgery", "신경외과")],
                        max_length=20,
                        verbose_name="진료과",
                    ),
                ),
                ("admission_date", models.DateTimeField(verbose_name="입원/진료 일시")),
                (
                    "discharge_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="퇴원 일시"
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        help_text="환자가 호소하는 주요 증상", verbose_name="주 호소"
                    ),
                ),
                (
                    "primary_diagnosis",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="주 진단명"
                    ),
                ),
                (
                    "secondary_diagnoses",
                    models.JSONField(
                        blank=True, default=list, verbose_name="부 진단명"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "attending_doctor",
                    models.ForeignKey(
                        limit_choices_to={"role__code": "DOCTOR"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encounters_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당 의사",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encounters",
                        to="patients.patient",
                        verbose_name="환자",
                    ),
                ),
            ],
            options={
                "verbose_name": "진료",
                "verbose_name_plural": "진료 목록",
                "db_table": "encounters",
                "ordering": ["-admission_date"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-admission_date"],
                        name="encounters_patient_ac188a_idx",
                    ),
                    models.Index(
                        fields=["attending_doctor", "-admission_date"],
                        name="encounters_attendi_b99851_idx",
                    ),
                    models.Index(
                        fields=["status"], name="encounters_status_2bbb51_idx"
                    ),
                ],
            },
        ),
    ]
