# Generated by Django 5.1.6 on 2026-01-11 07:31

from django.db import migrations, models


def convert_status_to_snake_case(apps, schema_editor):
    """기존 'in-progress' 데이터를 'in_progress'로 변환"""
    Encounter = apps.get_model('encounters', 'Encounter')
    Encounter.objects.filter(status='in-progress').update(status='in_progress')


def convert_status_to_hyphen(apps, schema_editor):
    """롤백: 'in_progress'를 'in-progress'로 복원"""
    Encounter = apps.get_model('encounters', 'Encounter')
    Encounter.objects.filter(status='in_progress').update(status='in-progress')


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0001_initial"),
    ]

    operations = [
        # 1. 먼저 데이터 변환
        migrations.RunPython(
            convert_status_to_snake_case,
            convert_status_to_hyphen,
        ),
        # 2. 그 다음 필드 choices 변경
        migrations.AlterField(
            model_name="encounter",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "예정"),
                    ("in_progress", "진행중"),
                    ("completed", "완료"),
                    ("cancelled", "취소"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
