# Generated by Django 5.1.6 on 2026-01-07 06:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("encounters", "0001_initial"),
        ("patients", "0002_alter_patient_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagingStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("CT", "CT (Computed Tomography)"),
                            ("MRI", "MRI (Magnetic Resonance Imaging)"),
                            ("PET", "PET (Positron Emission Tomography)"),
                            ("X-RAY", "X-Ray"),
                        ],
                        max_length=20,
                        verbose_name="검사 종류",
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        default="brain", max_length=100, verbose_name="촬영 부위"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "오더 생성"),
                            ("scheduled", "검사 예약"),
                            ("in-progress", "검사 수행 중"),
                            ("completed", "검사 완료"),
                            ("reported", "판독 완료"),
                            ("cancelled", "취소"),
                        ],
                        default="ordered",
                        max_length=20,
                        verbose_name="검사 상태",
                    ),
                ),
                (
                    "ordered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="오더 일시"
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="예약 일시"
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="검사 수행 일시"
                    ),
                ),
                (
                    "study_uid",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Study Instance UID",
                    ),
                ),
                (
                    "series_count",
                    models.IntegerField(default=0, verbose_name="시리즈 수"),
                ),
                (
                    "instance_count",
                    models.IntegerField(default=0, verbose_name="이미지 수"),
                ),
                (
                    "clinical_info",
                    models.TextField(blank=True, verbose_name="임상 정보"),
                ),
                (
                    "special_instruction",
                    models.TextField(blank=True, verbose_name="특별 지시사항"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imaging_studies",
                        to="encounters.encounter",
                        verbose_name="진료",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordered_imaging_studies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="오더 의사",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imaging_studies",
                        to="patients.patient",
                        verbose_name="환자",
                    ),
                ),
                (
                    "radiologist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="read_imaging_studies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="판독의",
                    ),
                ),
            ],
            options={
                "verbose_name": "영상 검사",
                "verbose_name_plural": "영상 검사 목록",
                "db_table": "imaging_studies",
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="ImagingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("findings", models.TextField(verbose_name="판독 소견")),
                ("impression", models.TextField(verbose_name="판독 결론")),
                (
                    "tumor_detected",
                    models.BooleanField(default=False, verbose_name="종양 발견 여부"),
                ),
                (
                    "tumor_location",
                    models.JSONField(blank=True, null=True, verbose_name="종양 위치"),
                ),
                (
                    "tumor_size",
                    models.JSONField(blank=True, null=True, verbose_name="종양 크기"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "작성 중"),
                            ("signed", "서명 완료"),
                            ("amended", "수정됨"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="판독문 상태",
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="서명 일시"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "radiologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imaging_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="판독의",
                    ),
                ),
                (
                    "imaging_study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="imaging.imagingstudy",
                        verbose_name="영상 검사",
                    ),
                ),
            ],
            options={
                "verbose_name": "영상 판독문",
                "verbose_name_plural": "영상 판독문 목록",
                "db_table": "imaging_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="imagingstudy",
            index=models.Index(
                fields=["patient", "ordered_at"], name="imaging_stu_patient_b9b5ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingstudy",
            index=models.Index(
                fields=["encounter"], name="imaging_stu_encount_e4430c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingstudy",
            index=models.Index(fields=["status"], name="imaging_stu_status_70677c_idx"),
        ),
        migrations.AddIndex(
            model_name="imagingstudy",
            index=models.Index(
                fields=["modality"], name="imaging_stu_modalit_30d44e_idx"
            ),
        ),
    ]
