# Generated by Django 5.1.6 on 2026-01-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imaging", "0001_initial"),
        ("ocs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagingstudy",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="imaging_study",
                to="ocs.order",
                verbose_name="OCS 오더",
            ),
        ),
    ]
