# Generated by Django 5.1.6 on 2026-01-08 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imaging", "0004_ocs_integration"),
        ("ocs", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="imagingstudy",
            new_name="imaging_stu_ocs_id_681f43_idx",
            old_name="imaging_stu_ocs_id_idx",
        ),
        migrations.RenameIndex(
            model_name="imagingstudy",
            new_name="imaging_stu_study_u_e67450_idx",
            old_name="imaging_stu_study_uid_idx",
        ),
        migrations.AlterField(
            model_name="imagingstudy",
            name="ocs",
            field=models.OneToOneField(
                help_text="연결된 OCS 오더 (job_role=RIS)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imaging_study",
                to="ocs.ocs",
                verbose_name="OCS 오더",
            ),
        ),
    ]
