# Generated by Django 5.1.3 on 2025-12-30 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("menus", "0002_delete_menurole"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="accounts.permission"
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="menus.menu",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission", "menu")},
        ),
    ]
