# Generated by Django 5.1.6 on 2026-01-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rolepermission",
            options={"managed": False},
        ),
    ]
