# Generated by Django 5.1.6 on 2026-01-09 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_rolepermission_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="rolepermission",
            table="accounts_rolepermission",
        ),
    ]
