# Generated by Django 5.1.6 on 2026-01-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rolepermissionhistory"),
        ("accounts", "0007_userprofile_department_userprofile_workstation"),
    ]

    operations = []
