# Generated by Django 5.1.6 on 2026-01-07 02:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_number",
                    models.CharField(
                        help_text="자동 생성됨 (예: P2026010001)",
                        max_length=20,
                        unique=True,
                        verbose_name="환자번호",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("birth_date", models.DateField(verbose_name="생년월일")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "남성"), ("F", "여성")],
                        max_length=1,
                        verbose_name="성별",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="전화번호 형식: 010-1234-5678",
                                regex="^\\d{2,3}-\\d{3,4}-\\d{4}$",
                            )
                        ],
                        verbose_name="전화번호",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="이메일"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="주소")),
                (
                    "ssn",
                    models.CharField(
                        help_text="암호화되어 저장됨",
                        max_length=255,
                        unique=True,
                        verbose_name="주민등록번호",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="혈액형",
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["페니실린", "조영제"] 형식',
                        verbose_name="알레르기",
                    ),
                ),
                (
                    "chronic_diseases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["고혈압", "당뇨"] 형식',
                        verbose_name="기저질환",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "활성"),
                            ("inactive", "비활성"),
                            ("deceased", "사망"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제여부"),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_patients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
            ],
            options={
                "verbose_name": "환자",
                "verbose_name_plural": "환자 목록",
                "db_table": "patients",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient_number"], name="patients_patient_dd5a30_idx"
                    ),
                    models.Index(fields=["name"], name="patients_name_2f3b76_idx"),
                    models.Index(fields=["phone"], name="patients_phone_ef6690_idx"),
                    models.Index(fields=["status"], name="patients_status_7c14f6_idx"),
                    models.Index(
                        fields=["-created_at"], name="patients_created_d307a3_idx"
                    ),
                ],
            },
        ),
    ]
