# Generated by Django 5.1.6 on 2026-01-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "남성"), ("F", "여성"), ("O", "기타")],
                max_length=1,
                verbose_name="성별",
            ),
        ),
    ]
