# Generated by Django 5.1.6 on 2026-01-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_add_user_to_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="chief_complaint",
            field=models.TextField(blank=True, null=True, verbose_name="주 호소"),
        ),
    ]
