# Generated by Django 5.1.6 on 2026-01-13 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="고유 식별 코드 (예: M1, MG, MM)",
                        max_length=20,
                        unique=True,
                        verbose_name="모델 코드",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="사용자 친화적 모델명",
                        max_length=100,
                        verbose_name="모델명",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="모델 설명 및 용도", verbose_name="설명"
                    ),
                ),
                (
                    "ocs_sources",
                    models.JSONField(
                        default=list,
                        help_text='입력 데이터 소스 (예: ["RIS"], ["LIS"], ["RIS", "LIS"])',
                        verbose_name="OCS 소스",
                    ),
                ),
                (
                    "required_keys",
                    models.JSONField(
                        default=dict,
                        help_text='모델별 필요 데이터 키 (예: {"RIS": ["dicom.T1", "dicom.T2"]})',
                        verbose_name="필요 데이터 키",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", max_length=20, verbose_name="모델 버전"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="모델별 추가 설정 (타임아웃, 배치 크기 등)",
                        verbose_name="추가 설정",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "AI 모델",
                "verbose_name_plural": "AI 모델 목록",
                "db_table": "ai_model",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AIInferenceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        help_text="사용자 친화적 ID (예: ai_req_0001)",
                        max_length=30,
                        unique=True,
                        verbose_name="요청 ID",
                    ),
                ),
                (
                    "ocs_references",
                    models.JSONField(
                        default=list,
                        help_text="사용된 OCS ID 목록",
                        verbose_name="OCS 참조",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        default=dict,
                        help_text="worker_result에서 추출한 입력 데이터",
                        verbose_name="입력 데이터",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기 중"),
                            ("VALIDATING", "검증 중"),
                            ("PROCESSING", "처리 중"),
                            ("COMPLETED", "완료"),
                            ("FAILED", "실패"),
                            ("CANCELLED", "취소됨"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("normal", "보통"),
                            ("high", "높음"),
                            ("urgent", "긴급"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="요청 일시"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="시작 일시"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 일시"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="에러 메시지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_inference_requests",
                        to="patients.patient",
                        verbose_name="환자",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_inference_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inference_requests",
                        to="ai_inference.aimodel",
                        verbose_name="AI 모델",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 추론 요청",
                "verbose_name_plural": "AI 추론 요청 목록",
                "db_table": "ai_inference_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIInferenceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        default=dict,
                        help_text="모델별 결과 데이터",
                        verbose_name="결과 데이터",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="0.0 ~ 1.0",
                        null=True,
                        verbose_name="신뢰도",
                    ),
                ),
                (
                    "visualization_paths",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="시각화 파일 경로들",
                        verbose_name="시각화 파일 경로",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "검토 대기"),
                            ("approved", "승인됨"),
                            ("rejected", "거부됨"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="검토 상태",
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, null=True, verbose_name="검토 의견"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="검토 일시"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "inference_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="ai_inference.aiinferencerequest",
                        verbose_name="추론 요청",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_ai_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="검토자",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 추론 결과",
                "verbose_name_plural": "AI 추론 결과 목록",
                "db_table": "ai_inference_result",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIInferenceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "요청 생성"),
                            ("VALIDATED", "데이터 검증 완료"),
                            ("STARTED", "처리 시작"),
                            ("PROGRESS", "처리 진행"),
                            ("COMPLETED", "처리 완료"),
                            ("FAILED", "처리 실패"),
                            ("CANCELLED", "요청 취소"),
                            ("REVIEWED", "결과 검토"),
                        ],
                        max_length=20,
                        verbose_name="동작",
                    ),
                ),
                ("message", models.TextField(verbose_name="로그 메시지")),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="상세 정보"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "inference_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ai_inference.aiinferencerequest",
                        verbose_name="추론 요청",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 추론 로그",
                "verbose_name_plural": "AI 추론 로그 목록",
                "db_table": "ai_inference_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["inference_request"],
                        name="ai_inferenc_inferen_a642bc_idx",
                    ),
                    models.Index(
                        fields=["action"], name="ai_inferenc_action_f30544_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_inferenc_created_97002f_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="aiinferencerequest",
            index=models.Index(
                fields=["request_id"], name="ai_inferenc_request_531d34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinferencerequest",
            index=models.Index(fields=["status"], name="ai_inferenc_status_6eae19_idx"),
        ),
        migrations.AddIndex(
            model_name="aiinferencerequest",
            index=models.Index(
                fields=["patient"], name="ai_inferenc_patient_1834c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinferencerequest",
            index=models.Index(fields=["model"], name="ai_inferenc_model_i_3a8e6b_idx"),
        ),
        migrations.AddIndex(
            model_name="aiinferencerequest",
            index=models.Index(
                fields=["requested_by"], name="ai_inferenc_request_16dd36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinferencerequest",
            index=models.Index(
                fields=["priority"], name="ai_inferenc_priorit_97b664_idx"
            ),
        ),
    ]
