# Generated by Django 5.1.3 on 2025-12-30 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "menu_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("path", models.CharField(blank=True, max_length=200, null=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "group_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("breadcrumb_only", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menus.menu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                ("text", models.CharField(max_length=100)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="menus.menu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="menus.menu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menus.menu"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.permission",
                    ),
                ),
            ],
            options={
                "unique_together": {("menu", "permission")},
            },
        ),
    ]
