# Generated by Django 5.1.3 on 2025-12-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuRole",
        ),
    ]
